### ISSUE TITLE
Does not work with recent gradle versions

### ISSUE THREAD

**Issue by koppor** [redocksoft/classpath-to-file-gradle-plugin#2]
class com.redock.classpathtofile.listener.EmptyFileCollection overrides final method org.gradle.api.internal.file.AbstractFileCollection.getBuildDependencies()Lorg/gradle/api/tasks/TaskDependency;

**Comment by rocketraman** [comment]
PRs welcome, thanks.

**Comment by InAnYan** [comment]
@rocketraman Could you please also update the plugin on https://plugins.gradle.org?

It's not a problem to build the plugin locally, but it is more convenient to have it updated on global repository

**Comment by rocketraman** [comment]
> @rocketraman Could you please also update the plugin on https://plugins.gradle.org?
> 
> It's not a problem to build the plugin locally, but it is more convenient to have it updated on global repository

It's been submitted and is waiting for review by the gradle team.

**Comment by InAnYan** [comment]
Thanks!
